version: '3.8'

services:
  traefik:
    image: traefik:v2.9.8                                            
    container_name: router_traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json

  platzi_dev:
    container_name: platzi_dev
    build:
      context: ./services/platzi_fastapi_sql
      dockerfile: Dockerfile.dev
    command: ["/wait-for-it.sh", "pgsql_farm:5432", "--", "uvicorn", "main:api", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    restart: always
    volumes:
      -  ./services/platzi_fastapi_sql:/platzi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platzi_dev.rule=Host(`${PLATZI_DOMAIN_DEV}`)"
      - "traefik.http.services.platzi_dev.loadbalancer.server.port=${PLATZI_PORT_DEV}"
      - "traefik.http.routers.platzi_dev.entrypoints=websecure"
      - "traefik.http.routers.platzi_dev.tls.certresolver=letsencrypt"
    environment:
      - TZ=America/Bogota
      - API_VERSION=${PLATZI_VERSION}
      - MODE=development
      - DEBUG=true
      - DB_URL=postgresql://${DB_USER}:${DB_PASS}@pgsql_farm:${DB_PORT}/${DB_NAME_PLATZI}

  pgsql_farm:
    image: postgres:15.2
    container_name: pgsql_farm
    restart: always
    volumes:
      - db_farm:/var/lib/postgresql/data/
      - ./scripts/db-init_sql.sh:/docker-entrypoint-initdb.d/db-init_sql.sh
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      # Databases
      - FARM_DB=${DB_NAME_FARM}
      - PLATZI_DB=${DB_NAME_PLATZI}

volumes:
  db_farm:
