version: '3.8'

services:
  traefik:
    image: traefik:v2.9.8                                            
    container_name: router_traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./services/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json

  platzi_dev:
    container_name: platzi_dev
    build:
      context: ./services/platzi_fastapi_sql
      dockerfile: Dockerfile.dev
    command: uvicorn main:api --host 0.0.0.0 --port ${PLATZI_PORT_DEV} --reload
    restart: always
    volumes:
      -  ./services/platzi_fastapi_sql:/platzi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.platzi_dev.rule=Host(`${PLATZI_DOMAIN_DEV}`)"
      - "traefik.http.services.platzi_dev.loadbalancer.server.port=${PLATZI_PORT_DEV}"
      - "traefik.http.routers.platzi_dev.entrypoints=websecure"
      - "traefik.http.routers.platzi_dev.tls.certresolver=letsencrypt"
    environment:
      - TZ=America/Bogota
      - API_VERSION=${PLATZI_VERSION}
      - MODE=development
      - DEBUG=true
